### ISSUE TITLE
Sample command "hive -f /opt/files/store_sales.sql" is failing

### ISSUE THREAD

**Issue by jletroui** [prasanthj/docker-hive-on-tez#1]
Here is the full session output I have:

```
$ docker --tls run -itP --rm prasanthj/docker-hive-on-tez /etc/hive-bootstrap.sh
Starting postgresql server...
/
2015-04-23 18:30:23 GMT LOG:  database system was interrupted; last known up at 2014-12-11 08:00:10 GMT
2015-04-23 18:30:23 GMT LOG:  database system was not properly shut down; automatic recovery in progress
2015-04-23 18:30:23 GMT LOG:  redo starts at 0/1782A58
2015-04-23 18:30:23 GMT LOG:  record with zero length at 0/18AFD10
2015-04-23 18:30:23 GMT LOG:  redo done at 0/18AFCE0
2015-04-23 18:30:23 GMT LOG:  last completed transaction was at log time 2014-12-11 08:00:11.97109+00
2015-04-23 18:30:23 GMT LOG:  autovacuum launcher started
2015-04-23 18:30:23 GMT LOG:  database system is ready to accept connections
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.5.2/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/tez/tez-dist/target/tez-0.5.2/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Starting namenodes on [8d37713d7cf7]
8d37713d7cf7: starting namenode, logging to /usr/local/hadoop/logs/hadoop-root-namenode-8d37713d7cf7.out
localhost: starting datanode, logging to /usr/local/hadoop/logs/hadoop-root-datanode-8d37713d7cf7.out
Starting secondary namenodes [0.0.0.0]
0.0.0.0: starting secondarynamenode, logging to /usr/local/hadoop/logs/hadoop-root-secondarynamenode-8d37713d7cf7.out
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.5.2/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/tez/tez-dist/target/tez-0.5.2/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
starting yarn daemons
starting resourcemanager, logging to /usr/local/hadoop/logs/yarn--resourcemanager-8d37713d7cf7.out
localhost: starting nodemanager, logging to /usr/local/hadoop/logs/yarn-root-nodemanager-8d37713d7cf7.out
Leaving namenode safemode...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.5.2/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/tez/tez-dist/target/tez-0.5.2/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Safe mode is OFF
root@8d37713d7cf7:/# hive -f /opt/files/store_sales.sql

Logging initialized using configuration in file:/usr/local/hive-dist/apache-hive-0.15.0-SNAPSHOT-bin/conf/hive-log4j.properties
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.5.2/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hive-dist/apache-hive-0.15.0-SNAPSHOT-bin/lib/hive-jdbc-0.15.0-SNAPSHOT-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/tez/tez-dist/target/tez-0.5.2/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2015-04-23 18:33:26 GMT ERROR:  syntax error at or near "@@" at character 5
2015-04-23 18:33:26 GMT STATEMENT:  SET @@session.sql_mode=ANSI_QUOTES
2015-04-23 18:33:26 GMT ERROR:  relation "v$instance" does not exist at character 21
2015-04-23 18:33:26 GMT STATEMENT:  SELECT version FROM v$instance
2015-04-23 18:33:26 GMT ERROR:  column "version" does not exist at character 10
2015-04-23 18:33:26 GMT STATEMENT:  SELECT @@version
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: File does not exist: hdfs://8d37713d7cf7:9000/tez/lib
    at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:458)
    at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:634)
    at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:578)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
Caused by: java.io.FileNotFoundException: File does not exist: hdfs://8d37713d7cf7:9000/tez/lib
    at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1072)
    at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1064)
    at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
    at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1064)
    at org.apache.tez.client.TezClientUtils.checkAncestorPermissionsForAllUsers(TezClientUtils.java:878)
    at org.apache.tez.client.TezClientUtils.addLocalResources(TezClientUtils.java:222)
    at org.apache.tez.client.TezClientUtils.setupTezJarsLocalResources(TezClientUtils.java:197)
    at org.apache.tez.client.TezClient.getTezJarResources(TezClient.java:711)
    at org.apache.tez.client.TezClient.start(TezClient.java:294)
    at org.apache.hadoop.hive.ql.exec.tez.TezSessionState.open(TezSessionState.java:191)
    at org.apache.hadoop.hive.ql.exec.tez.TezSessionState.open(TezSessionState.java:123)
    at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:455)
```

**Comment by prasanthj** [comment]
@jletroui I just pushed some changes updating the hive trunk version. Can you try it again and see if it fixes the issue? I am able to run the query locally on my system.

**Comment by jletroui** [comment]
@prasanthj Great, I confirm this is fixed now! Thank you very much!
